# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib imagine
engine1 <- function(data, kernel) {
    .Call('imagine_engine1', PACKAGE = 'imagine', data, kernel)
}

#' @importFrom Rcpp evalCpp
#' @useDynLib imagine
engine2 <- function(data, radius, x) {
    .Call('imagine_engine2', PACKAGE = 'imagine', data, radius, x)
}

