# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @useDynLib imagine, .registration = TRUE
NULL

engine1 <- function(data, kernel, noNA) {
    .Call(`_imagine_engine1`, data, kernel, noNA)
}

engine2 <- function(data, kernel, x) {
    .Call(`_imagine_engine2`, data, kernel, x)
}

engine3 <- function(data, radius) {
    .Call(`_imagine_engine3`, data, radius)
}

engine4 <- function(data, radius, x) {
    .Call(`_imagine_engine4`, data, radius, x)
}

