# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp evalCpp
#' @importFrom RcppArmadillo armadillo_version
#' @useDynLib imagine, .registration = TRUE
NULL

engine1 <- function(data, kernel) {
    .Call(`_imagine_engine1`, data, kernel)
}

engine2 <- function(data, kernel, probs) {
    .Call(`_imagine_engine2`, data, kernel, probs)
}

engine3 <- function(data, radius) {
    .Call(`_imagine_engine3`, data, radius)
}

engine4 <- function(data, radius, probs) {
    .Call(`_imagine_engine4`, data, radius, probs)
}

is_extreme <- function(in_mat, direction) {
    .Call(`_imagine_is_extreme`, in_mat, direction)
}

engine5 <- function(data) {
    .Call(`_imagine_engine5`, data)
}

